Support $PATH in the environment script

diff --git a/templates/env.sh.erb b/templates/env.sh.erb
--- a/templates/env.sh.erb
+++ b/templates/env.sh.erb
@@ -1,1 +1,102 @@
+#!/bin/sh
+#
+# Activate the environment used by Build CouchDB.
+# This script is idempotent and runs silently when not connected to a terminal.
 
+original_under="$_"
+
+this_file="$BASH_SOURCE"
+if [ -z "$this_file" ]; then
+    this_file="$0"
+fi
+
+# Since this script sets the environment, it must be sourced. Since running it
+# in a subshell is pointless, detect if that happened and warn the user.
+#
+# Detection confirmed to work for ./env.sh, . env.sh, source env.sh, $SHELL env.sh for all of:
+#  * Bash
+#  * Zsh
+#  * Dash
+if [ $(basename -- "$0") = 'env.sh' ]; then
+    err="This script must be sourced, not run standalone"
+
+    if [ "$ZSH_VERSION" ]; then
+        # Re-confirm for Zsh since the above test does not work.
+        if [ "$original_under" != "$0" ]; then
+            echo "$err" >&2
+            exit 1
+        fi
+    else
+        echo "$err" >&2
+        exit 1
+    fi
+fi
+
+main () {
+    <% unless pre_path_dirs.empty? %>
+        for pre_dir in <%= pre_path_dirs.map{|x| "'#{x}'" }.join(' ') %>; do
+            to_path 'insert' "$pre_dir"
+        done
+    <% end %>
+
+    <% unless post_path_dirs.empty? %>
+        for post_dir in <%= post_path_dirs.map{|x| "'#{x}'"}.join(' ') %>; do
+            to_path 'append' "$post_dir"
+        done
+    <% end %>
+}
+
+puts ()
+{
+    if [ -t 2 ]; then
+        echo "$*" >&2
+    fi
+}
+
+abspath () {
+    if [ `uname` = 'Darwin' ]; then
+        ruby -e "puts File.expand_path('$1')"
+    else
+        readlink -f "$1"
+    fi
+}
+
+# Idempotently add a directory into the search path.
+to_path () {
+    add_type="$1"
+    desired="$2"
+
+    if [ ! -d "$desired" ]; then
+        mkdir -p "$desired"
+    fi
+
+    desired=`abspath "$desired"`
+
+    if ! echo "$PATH" | grep "$desired" > /dev/null; then
+        if [ "$add_type" = 'insert' ]; then
+            puts "Inserting to PATH: $desired"
+            PATH="$desired:$PATH"
+        elif [ "$add_type" = 'append' ]; then
+            puts "Appending to PATH: $desired"
+            PATH="$PATH:$desired"
+        else
+            "Woa, what's going on here? $add_type $desired"
+        fi
+    fi
+}
+
+main
+
+# Clean up.
+unset desired
+unset pre_dir
+unset post_dir
+unset add_type
+unset this_file
+unset greppable_path
+unset original_under
+
+unset main
+unset puts
+unset abspath
+unset to_path
